name: pconnect
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  get: ^4.7.2
  get_storage: ^2.1.1
  dio: ^5.9.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  google_fonts: ^6.3.2
  image_picker: ^1.2.0
  file_picker: ^10.3.3
  socket_io_client: ^3.1.2
  flutter_local_notifications: ^19.4.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.8.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:

  uses-material-design: true
